---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helloworld-secret
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./cluster/my-cluster
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: ""

