apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzaWJhYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiIyOGIyNTY4Ny1jZDVlLTRiZDctYTg1Ny1kNzJhMzdkMWZiMzAiLCJwYXNzd29yZCI6InJnTDJ6OFdxOVVtfjlyOTRSb0RYSVhtN3N+bnpySmc5WTIiLCJhdXRoIjoiTWpoaU1qVTJPRGN0WTJRMVpTMDBZbVEzTFdFNE5UY3RaRGN5WVRNM1pERm1Zak13T25KblRESjZPRmR4T1ZWdGZqbHlPVFJTYjBSWVNWaHROM04rYm5weVNtYzVXVEk9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
